CREATE TABLE DW.DM_Professor(
	COD_PROF INT NOT NULL IDENTITY,
	MAT_PROF VARCHAR(20) NOT NULL,
	NOM_PROF VARCHAR(100) NOT NULL,
	TITULACAO VARCHAR(20) NULL,
	ENDERECO VARCHAR(50) NULL
);

ALTER TABLE DW.DM_Professor
   ADD CONSTRAINT PK_DM_Professor_COD_PROF PRIMARY KEY CLUSTERED (COD_PROF);

ALTER TABLE DW.FT_Nota
ADD CONSTRAINT COD_PROF
FOREIGN KEY (COD_PROF) REFERENCES DW.DM_Professor(COD_PROF);
