CREATE TABLE DW.FT_Nota(
	COD_NOTA INT NOT NULL IDENTITY,
	COD_ALU INT NOT NULL,
	COD_TURMA INT NOT NULL,
	COD_PROF INT NOT NULL,
	COD_DISC INT NOT NULL,
	COD_CURSO INT NOT NULL,
	NOTA1 INT NOT NULL,
	NOTA2 INT NOT NULL,
	SITUACAO CHAR NOT NULL
);

ALTER TABLE DW.FT_Nota
   ADD CONSTRAINT PK_FT_Nota_COD_NOTA PRIMARY KEY CLUSTERED (COD_NOTA);
