CREATE TABLE DW.DM_Departamento(
	COD_DEP INT NOT NULL IDENTITY,
	NOM_DEP VARCHAR(100) NOT NULL
);

ALTER TABLE DW.DM_Departamento
   ADD CONSTRAINT PK_DM_Departamento_COD_DEP PRIMARY KEY CLUSTERED (COD_DEP);

ALTER TABLE DW.FT_Nota
ADD CONSTRAINT COD_DEP
FOREIGN KEY (COD_DEP) REFERENCES DW.DM_Departamento(COD_DEP);
