CREATE TABLE DW.DM_Aluno(
	COD_ALU INT NOT NULL IDENTITY,
	MAT_ALU VARCHAR(20) NOT NULL,
	NOM_ALU VARCHAR(100) NOT NULL,
	ANO_INGRESSO INT NOT NULL,
	ESTADO_CIVIL CHAR NULL,
	SEXO CHAR NULL
);

ALTER TABLE DW.DM_Aluno
   ADD CONSTRAINT PK_DM_Aluno_COD_ALU PRIMARY KEY CLUSTERED (COD_ALU);

ALTER TABLE DW.FT_Nota
ADD CONSTRAINT COD_ALU
FOREIGN KEY (COD_ALU) REFERENCES DW.DM_Aluno(COD_ALU);
