CREATE TABLE DW.DM_Disciplina(
	COD_DISC INT NOT NULL IDENTITY,
	NOM_DISC VARCHAR(100) NOT NULL,
	NUM_CREDITOS INT NOT NULL,
	NATUREZA CHAR NOT NULL
);

ALTER TABLE DW.DM_Disciplina
   ADD CONSTRAINT PK_DM_Disciplina_COD_DISC PRIMARY KEY CLUSTERED (COD_DISC);

ALTER TABLE DW.FT_Nota
ADD CONSTRAINT COD_DISC
FOREIGN KEY (COD_DISC) REFERENCES DW.DM_Disciplina(COD_DISC);
