CREATE TABLE DW.DM_Turma(
	COD_TURMA INT NOT NULL IDENTITY,
	ANO INT NOT NULL,
	PERIODO INT NOT NULL,
	SALA VARCHAR(2) NOT NULL
);

ALTER TABLE DW.DM_Turma
   ADD CONSTRAINT PK_DM_Turma_COD_TURMA PRIMARY KEY CLUSTERED (COD_TURMA);

ALTER TABLE DW.FT_Nota
ADD CONSTRAINT COD_TURMA
FOREIGN KEY (COD_TURMA) REFERENCES DW.DM_Turma(COD_TURMA);
