CREATE TABLE Operacional.Professor(
	COD_PROF INT NOT NULL IDENTITY,
	COD_DEP INT NOT NULL,
	MAT_PROF VARCHAR(20) NOT NULL,
	NOM_PROF VARCHAR(100) NOT NULL,
	TITULACAO VARCHAR(20) NULL,
	ENDERECO VARCHAR(50) NULL
);

ALTER TABLE Operacional.Professor
   ADD CONSTRAINT PK_Professor_COD_PROF PRIMARY KEY CLUSTERED (COD_PROF);

ALTER TABLE Operacional.Professor
ADD CONSTRAINT COD_DEP
FOREIGN KEY (COD_DEP) REFERENCES Operacional.Departamento(COD_DEP);
