CREATE TABLE Operacional.Aluno(
	COD_ALU INT NOT NULL IDENTITY,
	COD_CURSO INT NOT NULL,
	MAT_ALU VARCHAR(20) NOT NULL,
	NOM_ALU VARCHAR(100) NOT NULL,
	ANO_INGRESSO INT NOT NULL,
	ESTADO_CIVIL CHAR NULL,
	SEXO CHAR NULL
);

ALTER TABLE Operacional.Aluno
   ADD CONSTRAINT PK_Aluno_COD_ALU PRIMARY KEY CLUSTERED (COD_ALU);

ALTER TABLE Operacional.Aluno
ADD CONSTRAINT COD_CURSO
FOREIGN KEY (COD_CURSO) REFERENCES Operacional.Curso(COD_CURSO);
