CREATE TABLE Operacional.Curso(
	COD_CURSO INT NOT NULL IDENTITY,
	COD_DEP INT NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	NUM_CREDITOS INT NOT NULL,
	DURACAO INT NOT NULL
);

ALTER TABLE Operacional.Curso
   ADD CONSTRAINT PK_Curso_COD_CURSO PRIMARY KEY CLUSTERED (COD_CURSO);

ALTER TABLE Operacional.Curso
ADD CONSTRAINT COD_DEP
FOREIGN KEY (COD_DEP) REFERENCES Operacional.Departamento(COD_DEP);
