CREATE TABLE Operacional.Turma(
	COD_TURMA INT NOT NULL IDENTITY,
	COD_DISC INT NOT NULL,
	COD_PROF INT NOT NULL,
	ANO INT NOT NULL,
	PERIODO INT NOT NULL,
	SALA VARCHAR(2) NOT NULL
);

ALTER TABLE Operacional.Turma
   ADD CONSTRAINT PK_Turma_COD_TURMA PRIMARY KEY CLUSTERED (COD_TURMA);

ALTER TABLE Operacional.Turma
ADD CONSTRAINT COD_DISC
FOREIGN KEY (COD_DISC) REFERENCES Operacional.Disciplina(COD_DISC);

ALTER TABLE Operacional.Turma
ADD CONSTRAINT COD_PROF
FOREIGN KEY (COD_PROF) REFERENCES Operacional.Professor(COD_PROF);
