CREATE TABLE Operacional.Nota(
	COD_NOTA INT NOT NULL IDENTITY,
	COD_ALU INT NOT NULL,
	COD_TURMA INT NOT NULL,
	NOTA1 INT NOT NULL,
	NOTA2 INT NOT NULL
);

ALTER TABLE Operacional.Nota
   ADD CONSTRAINT PK_Nota_COD_NOTA PRIMARY KEY CLUSTERED (COD_NOTA);

ALTER TABLE Operacional.Nota
ADD CONSTRAINT COD_ALU
FOREIGN KEY (COD_ALU) REFERENCES Operacional.Aluno(COD_ALU);

ALTER TABLE Operacional.Nota
ADD CONSTRAINT COD_TURMA
FOREIGN KEY (COD_TURMA) REFERENCES Operacional.Turma(COD_TURMA);
